### ISSUE TITLE
Errors due to NextSeq2000 output file format

### ISSUE THREAD

**Issue by lsaund11** [bbi-lab/bbi-dmux#6]
The new NextSeq2000 RunParameters.xml file does not contain a RunStartDate line that the Nextseq500 one does, and this leads to the following error when running the bbi-dmux command: 

```
# ran
nextflow run bbi-dmux -c my_config.sh

# error
...
Jul-23 14:01:06.121 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'make_sample_sheet'

Caused by:
  Process `make_sample_sheet` terminated with an error exit status (1)

Command executed:

  make_sample_sheet.py --run_directory/dir/to/run

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/net/trapnell/vol1/home/lsaund11/.nextflow/assets/bbi-lab/bbi-dmux/bin/make_sample_sheet.py", line 160, in <module>
      run_info = get_run_info(args.run_directory)
    File "/net/trapnell/vol1/home/lsaund11/.nextflow/assets/bbi-lab/bbi-dmux/bin/make_sample_sheet.py", line 139, in get_run_info
      run_stats['date'] = run_start_date_node.text
  AttributeError: 'NoneType' object has no attribute 'text'
```

The RunParameters.xml file for the Nextseq2000 is attached.

[Nextseq2000_runParameters.txt](https://github.com/bbi-lab/bbi-dmux/files/4969330/Nextseq2000_runParameters.txt)

**Comment by hpliner** [comment]
Did this get fixed @brgew? I feel like it did...
